spring:
  profiles:
    active: dev
  batch:
    job:
      name: ${job.name:helloWorldJob}
    jdbc:
      initialize-schema: always
  datasource:
    driver: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/db/batch
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    com.example.demo: debug
