spring:
  profiles:
    active: dev
  batch:
    job:
      name: ${job.name:none}
      enabled: true
    jdbc:
      initialize-schema: always
  datasource:
    driver: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/db/batch
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    spring.batch.exam: debug
